[package]
name = "orx-linked-list"
version = "0.6.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "An efficient doubly linked list using thin references with a focus on better cache locality avoiding heap allocations by smart pointers."
license = "MIT"
repository = "https://github.com/orxfun/orx-linked-list/"
keywords = ["linked", "list", "vec", "array", "pinned"]
categories = ["data-structures"]

[dependencies]
orx-imp-vec = "0.9.4"
