[package]
name = "orx-linked-list"
version = "0.3.0"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "An actually useful linked list :) documentation will follow."
license = "MIT"
repository = "https://github.com/orxfun/orx-linked-list/"
keywords = ["linked", "list", "vec", "array", "pinned"]
categories = ["data-structures"]

[dependencies]
orx-imp-vec = "0.9.1"
