[package]
name = "orx-linked-list"
version = "3.0.1"
edition = "2021"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "A linked list implementation with unique features and an extended list of constant time methods providing high performance traversals and mutations."
license = "MIT"
repository = "https://github.com/orxfun/orx-linked-list/"
keywords = ["linked", "list", "doubly", "singly", "pinned"]
categories = ["data-structures", "rust-patterns", "no-std"]

[dependencies]
orx-pseudo-default = { version = "1.4", default-features = false }
orx-pinned-vec = "3.9"
orx-split-vec = "3.9"
orx-selfref-col = "2.0"

[dev-dependencies]
clap = { version = "4.5.17", features = ["derive"] }
criterion = "0.5"
rand = "0.8.5"
rand_chacha = "0.3.1"
test-case = "3.3.1"

[features]
default = ["validation"]
validation = []

[[bench]]
name = "doubly_shuffling_around"
harness = false
